name: Phasmocraft
main: com.sparkymc.phasmocraft.Phasmocraft
version: 1.0
api-version: 1.18
authors:
    - Sparky
    - Abraxas
load: POSTWORLD
commands:
    giveitem:
        description: a
        usage: b
        permission: c
    startround:
        description: a
        usage: b
        permission: c
permissions:
    c:
        description: a
        default: op